package:
  name: cpprest
  version: 2.10.1

source:
  git_rev: v2.10.1a
  git_url: https://github.com/eisber/cpprestsdk

requirements:
  build:
    - boost-cpp
    - cmake
    - zlib
    - openssl

about:
  home: https://github.com/Microsoft/cpprestsdk
  license: MIT
  license_file: license.txt
